### ISSUE TITLE
App crash on API 21

### ISSUE THREAD

**Issue by DmitriSerhienko** [mirzemehdi/KMPNotifier#72]
**KMPNotifier and Kotlin version:**
 [e.g]: kmpnotifier version: 1.2.1, kotlin version: 2.0.0

have a crash on API 21 when push notification in viewmodel, like this:
val notifier = NotifierManager.getLocalNotifier()
notifier.notify(
                                title = getString(Res.string.app_name),
                                body = getString(Res.string.init_day)
                            )
on API 24 works perfectly

 E  FATAL EXCEPTION: main
                 Process: com.wgsoftpro.globinosales, PID: 6525
                 android.app.RemoteServiceException: Bad notification posted from package com.wgsoftpro.globinosales: Couldn't create icon: StatusBarIcon(pkg=com.wgsoftpro.globinosalesuser=0 id=0x7f070090 level=0 visible=true num=0 )
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1441)
                 	at android.os.Handler.dispatchMessage(Handler.java:102)
                 	at android.os.Looper.loop(Looper.java:135)
                 	at android.app.ActivityThread.main(ActivityThread.java:5221)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at java.lang.reflect.Method.invoke(Method.java:372)
                 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by mirzemehdi** [comment]
Thank you for this report. But looks like this is related to icon itself. Can you please try it with different icon to see if it still occurs?


"I was facing the same problem. I noticed I was using Vector Drawable for small icon and this error occurred only on pre-lollipop devices. Using PNG resource for pre-lollipop devices fixed the issue" (source: https://stackoverflow.com/a/39360741)

Attaching related issues:
https://stackoverflow.com/questions/25317659/how-to-fix-android-app-remoteserviceexception-bad-notification-posted-from-pac

**Comment by DmitriSerhienko** [comment]
yes u are right, with another icon works

**Comment by DmitriSerhienko** [comment]
yes u are right, with another icon works

**Comment by DmitriSerhienko** [comment]
yes u are right, with another icon works
